version: '3'
services:
 mysql:
  container_name: ${MYSQLNAME}
  image: ${IMAGESQL}
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQLROOT}
    - MYSQL_ROOT_HOST=%
    - MYSQL_DATABASE=nextdom
    - MYSQL_USER=nextdom
    - MYSQL_PASSWORD=${MYSQLPWD}
    - TZ= ${TZ}
  restart: ${RESTARTSQL}
  expose:
    - "3306"
  ports:
    - "${MYSQLMAP}"
  volumes:
  - mysqldata:/var/lib/mysql

 apache2-php7:
  container_name: ${CNAME}
  #image: ${IMAGE}
  build:
    dockerfile: Dockerfile.develop
    context: .
    args:
      - MYSQLROOT=${MYSQLROOT}
  restart: ${RESTART}
  healthcheck:
    test: ["CMD","curl","-f","http://localhost/public/here.html"]
    interval: 10s
    timeout: 10s
  expose:
    - "22"
    - "80"
    - "443"
  ports:
    - "${SSHMAP}"
    - "${HTTPMAP}"
    - "${HTTPSMAP}"
  environment:
    - ROOT_PASSWORD=${ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQLDB}
    - MYSQL_USER=${MYSQLUSER}
    - MYSQL_HOST=${MYSQLHOST}
    - MYSQL_PORT=${MYSQLPORT}
    - MYSQL_USER_PWD=${MYSQLPWD}
    - VERSION=${VERSION}
    - TZ=${TZ}
  volumes:
    - wwwdata:/var/www/html/
  links:
   - mysql
  depends_on:
   - mysql
  stdin_open: true
  tty: true

volumes:
  wwwdata:
  mysqldata: